### ISSUE TITLE
create log files

### ISSUE THREAD

**Issue by tmgbdark** [TanguyOrtegat/AutomaticLinuxReboot#2]
bonjour je bloque a cette etape create log files pourrais tu m'aider

**Comment by TanguyOrtegat** [comment]
qu'et ce que tu comprend pas ?

**Comment by tmgbdark** [comment]
cette etape la entiere enfaite

**Comment by TanguyOrtegat** [comment]
en faite ls logs de tout ce que tu fais en vrais c'es pas super utile, c'est juste utile si un de tes script .sh ne fonctionne pas 
donc a la place de faire 
`*/2 * * * * bash /root/CheckCrashServer.sh >> /var/log/fxreload/fxreloadlog
01 12 * * * bash /home/FxServer/reload_fxserver.sh >> /var/log/fxreload/fxreloadlog
01 00 * * * bash /home/FxServer/reload_fxserver.sh >> /var/log/fxreload/fxreloadlog`

tu fais
`*/2 * * * * bash /root/CheckCrashServer.sh

01 12 * * * bash /home/FxServer/reload_fxserver.sh

01 00 * * * bash /home/FxServer/reload_fxserver.sh`

**Comment by tmgbdark** [comment]
ok et le reload je le place dans quel fichier

**Comment by TanguyOrtegat** [comment]
ou tu px, mais alors faut changer l'emplacement dans le crontab

**Comment by tmgbdark** [comment]
dans var/log jai pas fxreload

**Comment by TanguyOrtegat** [comment]
oui normal
t'en a pas besoin c'etait des logs au cas ou ...

**Comment by tmgbdark** [comment]
pourquoi quand je les lance manuellement sa me marque acces refuser sur les fichier tu a donner

**Comment by TanguyOrtegat** [comment]
t'es bien avec ton compte root ?

**Comment by tmgbdark** [comment]
OUI

**Comment by TanguyOrtegat** [comment]
tu fais quelle commande pour les lancer ? t'es dans quels répertoire ?

**Comment by TanguyOrtegat** [comment]
no response closing tread
